gram/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from .import views
from .views import (
  # PostCreateView,
  PostListView,
  PostDetailView,

)
app_name = 'gram'
urlpatterns = [
    path('',PostListView.as_view(),name='allPosts'),
    path('new/<int:id>/',views.new_post,name='createPost'),
    path('<int:id>',PostDetailView.as_view(), name= 'postDetails'),
    path('search/',views.search_posts ,name='search_posts'),
    path('profile/', views.profile , name = 'profile'),
    path('update/',views.account_update,name='update'),
    path('comment/<int:id>/',views.all_comments,name='comment'),
    path('post_comment/<int:id>/',views.post_comment,name='postComment'),
    


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

instagram/urls.py
from django.conf.urls import url
from django.contrib import admin


from django.contrib.auth import views
from django.urls import path, include
from gram.views import account

# from account.views import login_view, register_view,logout_view
urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('gram.urls')),
    path('',account),
    # path('account/login/',login_view),
    # path('account/register/',register_view),
    # path('account/logout/',logout_view),
    path('tinymce/',include('tinymce.urls')),
    path('accounts/',include('registration.backends.simple.urls')),
    path('logout/' ,views.logout, {"next_page":'/'}),
    

]

gram/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from tinymce.models import HTMLField
from PIL import Image
from django.db.models.signals import post_save
from django.db import models
from django.utils import timezone

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='profile')
    
    profile_photo = models.ImageField(default='fur.jpg', upload_to='profile_pics')
    name = models.CharField(max_length=50)
    bio = models.TextField(max_length=250)
    follows = models.ManyToManyField('Profile', related_name='followed_by')


    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self,*args,**kwargs):
        super().save()
        
        img = Image.open(self.profile_photo.path)
        
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.profile_photo.path)

    # def create_user_profile(sender, instance, created, **kwargs):
    #     if created:
    #         Profile.objects.create(user=instance)

    #         post_save.connect(create_user_profile, sender=User)



class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    image = models.ImageField(null=True)
    caption = HTMLField(null=True)
    posted_date = models.DateTimeField(default=timezone.now)
    # comments = HTMLField(null=True)
    likes = models.TextField(null=True)
    profile = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True)


    @classmethod
    def search_by_author(cls,search_term):
        posts = cls.objects.filter(profile__icontains=search_term)
        return posts


    def __str__(self):
      return self.caption

    @classmethod
    def get_one_post(cls,id):
        post = cls.objects.get(pk=id)
        return post


    @classmethod
    def all_posts(cls):
        posts = cls.objects.all()
        return posts


    def save_post(self):
        super().save()
    def delete_post(self):
        return self.delete()

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    comment = models.CharField(max_length=230,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    
    commented_on = models.DateTimeField(auto_now_add=True)

    def save_comment(self):
        self.save()
    
    
    @classmethod
    def all_comments(cls,id):
        comments = cls.objects.filter(post__id=id)
        return comments
    
    
    def __str__(self):
        
        return self.comment
        
    
     

gram/forms.py
from django import forms
from .models import Post,Profile,Comment
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from  crispy_forms.layout import Submit,Layout,Field


class UserPostForm(forms.ModelForm):
  helper =FormHelper()
  helper.form_method ='POST'
  helper.add_input(Submit('Post','Post',css_class='btn-primary'))
  class Meta:
     model = Post
     fields =[
       'image',
       'caption'
     ]
  def save(self,commit=True):
    user = super().save(commit=False)
    if commit:
      user.save()
    return user

# class UserPostForm(forms.ModelForm):
#     class Meta:
#         model = Post
#         exclude = ['author', 'posted_date','comments','likes']
       
class DetailsUpdate(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ['profile_photo','bio']  

class CommentPostForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['user','post','comment_on']
    
     

    
class AccountUpdate(forms.ModelForm):
  email = forms.EmailField()
  class Meta:
    model = User
    fields = ['username','email']

gram/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404,redirect
from .models import Post,Profile,Comment
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from .forms import  UserPostForm,AccountUpdate,DetailsUpdate,CommentPostForm
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib import messages
from django.views.generic import(
  ListView,
  CreateView,
  DetailView,

)

# Create your views here.
# @login_required(login_url='/accounts/login/')
class PostListView(LoginRequiredMixin,ListView):
  template_name = 'gram/post_list.html'
  queryset = Post.objects.all()[::-1]
  context_object_name ='posts'
  class Meta:
    ordering = ['posted_date']

# @login_required(login_url='/accounts/login/')
# class PostCreateView(LoginRequiredMixin,CreateView):
#   template_name = 'gram/create.html'
#   form_class = PostForm
#   queryset = Post.objects.all()
#   success_url = '/' 

#   def form_valid(self,form):
#      print (form.cleaned_data)
#      form.instance.author = self.request.user
#      form.save()
#      return super().form_valid(form)

# @login_required(login_url='/accounts/login/')



def post_comment(request,id):

    current_user = request.user
    post = Post.get_one_post(id=id)
    if request.method == 'POST':
        form = CommentPostForm(request.POST)
        print(form)
        
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = current_user
            comment.post_id = id
            comment.save()
        return redirect('/')

    else:
        form = CommentPostForm()
        return render(request,'gram/post_comment.html',{"form":form,"post":post})  
    
def all_comments(request,id):
    comments = Comment.all_comments(id)
    number = len(comments)
    
    return render(request,'gram/comment.html',{"comments":comments,"number":number})   

class PostDetailView(LoginRequiredMixin,DetailView):
  queryset=Post.objects.all().filter(posted_date__lte=timezone.now())
  def get_object(self):
    id_=self.kwargs.get('id')
    return get_object_or_404(Post,id=id_)
    template_name = 'gram/post_detail.html'
# searching view
@login_required(login_url='/accounts/login/')

def search_posts(request):
    if 'user' in request.GET and request.GET['user']:
      search_term = request.GET.get('user')
      searched_users = Post.search_by_author(search_term)
      message = f'{search_term}'
      return render (request, 'gram/search.html',{'message':message,'users':searched_users})
    else:
      message = "Nothing was searched.Please ensure you type something"
      return render (request, 'gram/search.html',{'message':message})


      # try different auth
@login_required
def account(request):
  return render (request,'account.html',{})      

@login_required(login_url='/accounts/login/')
def new_post(request,id):
    current_user = request.user
    if request.method == 'POST':
        form = UserPostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = current_user
            post.save()
        return HttpResponseRedirect('/')

    else:
        form =UserPostForm()
    return render(request, 'gram/create.html', {"form": form})


@login_required
def account_update(request):
  
  # if request.method == 'POST':
  #   try:
  #     profile = request.user.profile
  #   except Profile.DoesNotExist:
  #     profile = Profile(user=request.user)
  if request.method == 'POST':
       user_form = AccountUpdate(request.POST,instance=request.user)
       details_form = DetailsUpdate(request.POST ,request.FILES,instance=request.user.profile)
       if user_form.is_valid() and details_form.is_valid():
          user_form.save()
          details_form.save()
          messages.success(request,f'Your Profile account has been updated successfully')
          return redirect('gram:profile')
  else:
  

      user_form = AccountUpdate(instance=request.user)
      
      details_form = DetailsUpdate(instance=request.user.profile) 
  forms = {
    'user_form':user_form,
    'details_form':details_form
  }
  return render(request,'gram/update_info.html',forms)




@login_required
def profile(request):
  current_user = request.user
  
  profile = Profile.objects.get_or_create(user=request.user)
  images = request.user.post_set.all()
  
  post = images.count()
  
  
  return render(request,'gram/profile.html',{"profile":profile,'images':images,"post":post})

gram/templates/gram/base.html
{% load static %}
{%load bootstrap4%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
   <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/vs.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> --> -->
<link rel="stylesheet" href="{% static 'css/styles.css'%}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>Instagram</title>

  {% block styles %}
    {% bootstrap_css %}
  {% endblock %}

</head>

<body>
  <header>
    <div class="nav">
      <div class="logo">
        <a href="/" class="ig"><i class="fa fa-instagram"></i></a>
        <a class="verticle" href="/"></a>
        <!-- <a href="/">Instagram</a> -->
        <img src="/static/ig.png" alt="" style="width: 100px; height: 40px; font-weight: bolder;">
      </div>
      <form action="{% url 'gram:search_posts'%}">
      <div class="search">
        
          <input type="text" placeholder="search" name="user">
        <a href="{% url 'gram:search_posts'%}">
          <button><i class="fa fa-search"></i></a></button>
</form>

<div class="col-sm-6 col-md-6" >
  {% if user.is_authenticated %}
  <ul>
    <li>
      <a href="{% url 'gram:update'%}">{{user.username}}
                <span class="caret"></span>
            </a>
      <ul class="dropdown-menu" role="menu">
        
        <li>
          <a href="/gram/templates/gram/create.html">Create Article</a>
        </li>

        <li>
          <a href="/accounts/password/change">Change Password</a>
        </li>
        <li>
          <a href="/logout">Logout</a>
        </li>
      </ul>
    </li>
  </ul>
  {% else %}
  <li>
    <a class='btn btn-default' href="/accounts/login">Login</a>
  </li>

  {% endif %}
</div>
      </div>
      <div class="icons">
        <!-- <a href="" class="compass"><i class="fa fa-compass"></i></a>
       -->
        <a href="{% url 'gram:createPost' user.id%}" class="compass"><i class="fa fa-plus"></i></a>
        <a href="/" class="heart"><i class="fa fa-heart"></i></a>
        <a href="{% url 'gram:profile' %}" class="profile"><i class="fa fa-user"></i></a>

      </div>
    </div>
  </header>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>

  <hr>
  

  <div class="content">
    {%block content%}
    {% endblock%}
  </div>

  {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="path/to/boostrap.min.js"></script>

  {% bootstrap_javascript %}
{% endblock %}


  
</body>

</html>

gram/templates/gram/comment.html
{% extends 'gram/base.html'%}

{% block content %}
{% if comments %}
<div class="container">
    {% if number == 1 %}
        <i class="text-center">{{number}} comment</i>
    {% else %}
    <i class="text-center">{{number}} comments</i>
    {% endif %}
{% for comment in comments %}
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
    <div class="card" style="width: 30rem;">
        <div class="card-header">
            <h4 class="text-center mycom">{{comment.user.username}}</h4>
                <span><hr></span>
               <span class="mr-5"> <img src="{{comment.user.profile.profile_photo.url}}" alt=""
                style="border-radius: 50%; width:50px; height:50px; border-color: brown; border-width: 1px;"></span>
             
                <span class="text-center">{{comment.comment}}</span>
               </div>
       

    </div>
</div>

<div class="col-sm-3"></div>
</div>

{% endfor %}
</div>
{% else %}
<p>no comments yet</p>
{% endif %}
{% endblock %}

gram/templates/gram/create.html
{%extends 'gram/base.html'%}
{% load bootstrap4%}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Instagram</title>
</head>
<body>
    {%block content%}
  <h1 style="text-align: center;">Create Post</h1>
  
<div class='panel panel-default' style="width: 400px; margin: auto;">
  <div class="panel-body">
    {%crispy form%}
    {%csrf_token%}
  </div>

</div>

{% endblock %}

{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% bootstrap_javascript %} {% endblock %}


</body>
</html>

gram/templates/gram/post_comment.html
{% load bootstrap4 %}
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>New Image</title>

    {% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/styles.css'%}">
    {% endblock %}
</head>

<body>
    <div class="container">
    <form action="{% url 'gram:postComment' post.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form%}
        <input type="submit" class="btn btn-success btn-lg" value="Post">
    </form>

    {% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% bootstrap_javascript %}
    {% endblock %}
    </div>
</body>

gram/templates/gram/post_detail.html
{%extends 'gram/base.html'%}
{% load bootstrap4%}

{%block content%}
  <img src="{{post.image.url}}" alt="" style="width:350px; height:350px;">
  
  <div class="row">
    {% autoescape on %}
    {{post.caption| safe}}
   {% endautoescape %}
   </div>

{% endblock %}

gram/templates/gram/post_list.html
{% extends 'gram/base.html'%}
  {% load bootstrap4%}
{%block content %}
{% for post in posts %}
<div class="card">
  <div class="card-header">
    <div class="pic">
      <img src="{{ post.author.profile.profile_photo.url }}" alt="">

    </div>
      <div class="info">
        <div class="name"><a href="" style="text-decoration: none;">{{post.author}}</a></div>
        <div class="location">Kenya</div>
      </div>
<div id="options"><i class="fa fa-ellipsis-h"></i>

</div>
    </div>
    <div id="image">
      <img src="{{post.image.url}}" alt="">
    </div>
    <div class="reactions">
<a href=""><i class="fa fa-heart"></i></a>
<a href="{%url 'gram:postComment' post.id %}"><i class="fa fa-comment"></i></a>
<a href="{% url 'gram:comment' post.id %}" class="btn btn-outline-info btn-sm">comments</a>

<a href=""><i class="fa fa-share"></i></a>
<a href=""><i class="fa fa-bookmark" style="float: right;margin-right:20px ;"></i></a>
    </div>
    <div class="like">
    <a href="" style="text-decoration: none;color:black; font-weight:bolder;padding:0px 23px;">likes</a>
</div>
<div class="cp">
  <a href="{% url 'gram:profile'%}"style="color: black; text-decoration: none;"><h4 >{{post.author}}</h4></a>
  
  {% autoescape on %}
    <span>{{post.caption| safe}}</span>
   {% endautoescape %}
  
</div>
<div id="time">{{post.posted_date | timesince}} ago</div>
  </div>


<!-- <p>{{post.author}}</p>
<p>{{post.caption}}</p>
<p>{{post.posted_date }}</p> -->
{% endfor %}
{%endblock%}

gram/templates/gram/profile.html
{%extends 'gram/base.html'%}
{% load bootstrap4%}

{%block content%}

<div class="row">

  <div class="col-md-6">
    <div class="ppic">
      <img src="{{user.profile.profile_photo.url}}" alt="">
    </div>
  </div>
  <div class="col-md-6">
    <h3>{{user.username}}</h3>
    <button><a href="{% url 'gram:update'%}" style="text-decoration: none;">EDIT PROFILE</a></button>
    <a href="{% url 'gram:update'%}"><i class="fa fa-cog" style='color:black;font-size: 30px;'></i></a>
    <div class="profile_media">
      <span class="post_count"> <span class="number_of_posts">{{ user.posts.count }}</span> posts </span>
      <a href=""> <span class="number_of_followers"> {{ user.profile.followed_by.count }}</span> followers</a>
      <a href=""> <span class="number_of_follows"> {{ user.profile.follows.count }} </span> following</a>
    <button><a href="/logout"></a>logout</button>
    </div>
    <div>
      <p class="profilename">{{ user.profile.name }}</p>
      <p class="text-secondary">{{ user.profile.bio|linebreaks }}</p>
    </div>
    <div class="profileicons" style="color: black;">

      <a href="#posts"><i class="fa fa-calendar"></i>
        POSTS
      </a>
      <a href="#igtv"><i class="fa fa-tv"></i>
        IGTV

      </a>
      <a href="#saved"><i class="fa fa-bookmark"></i>
        SAVED
      </a>


      <a href="#tagged"><i class="fa fa-user"></i>
        TAGGED
      </a>

    </div>
  </div>

</div>


<br>
<hr>

  <div class="row">

{% for image in images %}
<div class="col-md-3">
    <div class="card-column" >
      <img class="card-img-top" src="{{image.image.url}}" alt="Card image cap" style="width: 250px; height: 250px;">
      <div class="card-body">
       {% autoescape on %}
       <h5 class="card-title">{{image.caption | safe}}</h5>
   {% endautoescape %}
        <!-- <h5 class="card-title">{{image.caption}}</h5> -->
        <i class="fa fa-heart "></i>
        <a href="{% url 'gram:comment' image.id %}" class="btn btn-outline-info btn-sm">comments</a>
        

      </div>
    </div>
  
  </div>

{% endfor %}



</div>

{% endblock %}

gram/templates/gram/search.html
{%extends 'gram/base.html'%}
{% block content %}
<div class="container">

  <div class="row">
    {% if users %}
      <h2>Found {{ posts|length }} of searched term {{message}}</h2>
    {% else %}
    <h2> Found 0 users for the search term {{message}}</h2>
    {% endif %}

  </div>

  <div class="row">

    {% if users %}
    {% for user in users %}
    <div class="col-sm-6 col-md-3">
      <h1>{{user.author}}</h1>
    </div>
    {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock %}

gram/templates/gram/update_info.html
{%extends 'gram/base.html'%}
{% load bootstrap4%}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Instagram</title>
</head>
<body>
    {%block content%}
  <h1 style="text-align: center;">Update Profile</h1>
  <form action="" method="POST" enctype="multipart/form-data" class = "form2">
<div class='panel panel-default' style="width: 400px; margin: auto;">
  <div class="panel-body">
    <h5>Update Credentials</h5>
    {%csrf_token%}
    {{user_form|crispy}}
<h5 style="color:rgb(12, 12, 160)">update your profile</h5>
    {{details_form|crispy}}
    <button>Update Information</button>

    
  </div>

</div>
</form>

{% endblock %}

{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% bootstrap_javascript %} {% endblock %}


</body>
</html>